### ISSUE TITLE
visualization que

### ISSUE THREAD

**Issue by vehxianfish** [lpiccinelli-eth/UniDepth#16]
Hi, @lpiccinelli-eth, thanks for your wonderful open-source work!
I want to reproduce your nuscenes visualization result. 
The raw image is as bellows:
![image](https://github.com/lpiccinelli-eth/UniDepth/assets/40848953/9711fb78-65ae-4e3a-ba21-edc6265f2ee6)

The predicted pointcloud is as bellows:

![image](https://github.com/lpiccinelli-eth/UniDepth/assets/40848953/d17629f4-2604-4a40-847a-a0b08844ed1b)

There are two questions:
1. the right building is far away
2. the sky height is not high enough.

So, does above phenomenon is normal? thanks for your help.
best regards!

**Comment by lpiccinelli-eth** [comment]
Thank you for your appreciation!

The sky is a typical artifact due to the model never seeing ground truth for the sky (LiDAR GT is always "invalid" for sky region) and the model "lazily" converges to small values of depth in those regions, thus small height, too. However, our v2 (#15) will solve this problem.

On the other hand, the building is an artifact of the model which incorrectly predicts its depth as too far.

**Comment by vehxianfish** [comment]
Thanks!

**Comment by missTL** [comment]
Thank you. How do you get this visualization?
