### ISSUE TITLE
Is there a large loss in the x direction?

### ISSUE THREAD

**Issue by red-liu** [lpiccinelli-eth/UniDepth#47]
I found there is a larger error in the x direction. Is the model only used to predict depth, or is there a special configuration for the model?

**Comment by red-liu** [comment]
predicted intrinsic value: fx=1471.4409, fy=2411.942, cx=1517.1675, cy=2021.4147
The values of predicted intrinsic fx and fy are quite different, is there a problem?

**Comment by lpiccinelli-eth** [comment]
I doubt there is a problem with the inference. I remember some new datasets (like MegaDepth or similar)  that are COLMAP-based and present "weird" focal lengths for some scenes, especially `f_x`. It could be that your input image is similar to those MegaDepth scenes and the model just memorized those "weird" covariates, ie (image, depth, camera), since they are pretty off and there is not much data to hedge those "weird" covariates.

Anyway, thank you for pointing this out, we will dive deeper into this problem. One simple (temporary) solution on your side is to use only `f_y`.

**Comment by red-liu** [comment]
I appreciate your detailed answer regarding my question. thanks your great work.
